### ISSUE TITLE
add the possibility to translate the F designing the button for Fertigkeitsspezialisierung Wurfe / skill specialization roll

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#101]
line 1849 for the first skill `<button class="roll1w" name="tal_reiten_f" type="roll" value="@{output_option} &{template:DSA-Talente} {{name=^{reiten}}} {{subtags=^{mitspezialisierung}}} {{Talent=[[@{reiten_fw}+2-{1d20cs1cf20-([[@{reiten_eigenschaft1}]]+[[@{reiten_gesamt_mod}]]+@{mod_option}),0d1}kh1-{1d20cs1cf20-([[@{reiten_eigenschaft2}]]+[[@{reiten_gesamt_mod}]]+@{mod_option}),0d1}kh1-{1d20cs1cf20-([[@{reiten_eigenschaft3}]]+[[@{reiten_gesamt_mod}]]+@{mod_option}),0d1}kh1]]}} {{Modifikator=[[@{reiten_gesamt_mod}+@{mod_option}]]}}">F</button>`

the "F " at the end of this line is not tied to a data-i18n key. can you please add one?

the same operation has to be made for each skill from line 1849 to 9927

i used a CTRL+F searching `>F` to find all the lines

**Comment by dyvim** [comment]
note that the same thing should be made for Routineprobe / Routine checks but hopefully Routine seems to be translated the same way in most of the languages, so the R will stay a R.

**Comment by Plushtoast** [comment]
Btw haven't you been using foundry already? Why did you go to r20?

**Comment by dyvim** [comment]
@Plushtoast i use foundry as a player but never bought it for the moment. i'm not sure that my connection will be sufficient for foundry (only adsl)
as a GM i use roll20 almost every week for dsa/tde

**Comment by Plushtoast** [comment]
Foundry doesnt need a fast connection if you use voice/video on another tool btw

**Comment by Plushtoast** [comment]
See:
https://github.com/Roll20/roll20-character-sheets/pull/9802
