### ISSUE TITLE
autosize for the span class tab (ccs modification)

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#102]
line 1215  to 12162 of the html file
`    <input type="radio" name="attr_kampf_tab" class="tab kampftab1" value="1" />
    <span class="tab" data-i18n="kampftechniken">Kampftechniken</span>
    <input type="radio" name="attr_kampf_tab" class="tab kampftab2" value="2" checked />
    <span class="tab" data-i18n="nahkampf">Nahkampf</span>
    <input type="radio" name="attr_kampf_tab" class="tab kampftab3" value="3" />
    <span class="tab" data-i18n="fernkampf">Fernkampf</span>
    <input type="radio" name="attr_kampf_tab" class="tab kampftab4" value="4" />
    <span class="tab" data-i18n="patzer">Patzer</span>`

the css parameters of this class causes little display problems in some languages.
for example in french
![image](https://user-images.githubusercontent.com/8790994/141826629-c9ae3100-227c-4f4a-9910-57d5d5b3c3e9.png)
(we miss some text)

could it be possible to use autosize as a parameter for the corresponding css class?

**Comment by Plushtoast** [comment]
Autosize will mess with the entire layout. I don't think this is an option

**Comment by dyvim** [comment]
> Autosize will mess with the entire layout. I don't think this is an option

except if you create a specific class only for these 4 "buttons" perhaps
but yes modifying this class will have an impact on a lot of things in the sheet

**Comment by Plushtoast** [comment]
in the long term I intend to compress those four tabs into a single one

**Comment by dyvim** [comment]
that could be a good idea if the final tab is not too big

btw, it could be a good idea to relocate the botch rolls for spells and liturgical chants in the magic and liturgical tabs...
it makes no sense to have to go to the combat + botch tab when you cast a spell or a litugical chant and make a botch
(i'll open an other issue for that)

this issue can be closed so.
(i've shortened the french translations so that they will fit in the actual buttons)
