### ISSUE TITLE
SF-Mod im Reiter Kampf fehlerhaft

### ISSUE THREAD

**Issue by Bartgerecht** [Plushtoast/TDE-Roll20-Official#106]
Der SF-Mod im Reiter Kampf ist fehlerhaft. Wenn beispielsweise die SF Verteidigungshaltung unter Sonderfertigkeiten hinzugefügt, aber nicht aktiviert wurde, besteht automatisch ein SF-Mod von PA -4. Wird die SF aktiviert, geht der SF-Mod auf PA 0. Dieser Bug tritt bei allen Kampfsonderfertigkeiten auf.

**Comment by Plushtoast** [comment]
See:
https://github.com/Roll20/roll20-character-sheets/pull/9802
