### ISSUE TITLE
Schilde/Nebenhandwaffen Bug

### ISSUE THREAD

**Issue by 10jfk** [Plushtoast/TDE-Roll20-Official#111]
Es ist nicht möglich Nebenhandwaffen auszurüsten.
![grafik](https://user-images.githubusercontent.com/44535698/143659173-2376b8c6-72a8-475b-b353-f86be154cb8a.png)
Es fehlt Add. Und auch das hineinziehen aus dem Kompendium geht nicht.

**Comment by Plushtoast** [comment]
Wenn du die Details der Waffe ausklappst findet sich dort ein Schalter für nebenhand. Damit kannst du jederzeit die Hand wechseln, in der die Waffe geführt wird.
Da den Button anzeigen würde jedesmal die Waffe der Haupthand hinzufügen und Verwirrung stiften. Ein Button der das trotzdem erlaubt, ist in Planung.

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/143687453-1cfa225c-0277-41f9-9a55-0cf751c66893.png)
Das hier

**Comment by 10jfk** [comment]
Danke! Hat funktioniert.
