### ISSUE TITLE
Selbst angelegte Effekte - Eigenschaftsmodifikator +/- wird nicht erkannt

### ISSUE THREAD

**Issue by PapaNils** [Plushtoast/TDE-Roll20-Official#112]
Hallo,
ich habe mir einen Effekt angelegt und einen Eigenschafftsmodifikator Gewandheit +1 gepflegt.

Die Gewandheit wird auch mit aktivierten Effekt nicht erhöht. die anderen Eigenschaften reagieren auch nicht.

Der Lebensenergiefaktor funktioniert.
AT Faktor funktioniert auch.
Furcht klappt auch.

**Comment by Plushtoast** [comment]
Fix wird vorraussichtlich Anfang nächster Woche eingespielt:
https://github.com/Roll20/roll20-character-sheets/pull/9842
