### ISSUE TITLE
Vorteil "Eisern" und Modifikation für Wundschwelle fehlen

### ISSUE THREAD

**Issue by gavriel3** [Plushtoast/TDE-Roll20-Official#116]
Der Vorteil "Eisern" erhöht die Wundschwelle um 1. 
Da es diesen Vorteil im Kompendium nicht gibt wollte ich ihn manuell anlegen. Es gibt unter den Modifkationen alles mögliche an Talenten und Eigenschaften, nur die Wundschwelle nicht. Ich kann den Wert bei der Wundschwelle im Charaktersheet auch nicht überschreiben.

**Comment by Plushtoast** [comment]
Den Modifikator für die Wundschwelle wirds im nächsten Update geben.

**Comment by gavriel3** [comment]
danke
