### ISSUE TITLE
Highlighten Critical Dice Roll 

### ISSUE THREAD

**Issue by yutanima** [Plushtoast/TDE-Roll20-Official#117]
When rolling either a 1 or a 20 there seems to be an indicator in the message. Skillpoints are either highlighted in a pretty dark red or green. These colors hardly differ from the usual black that is used as an indicator for the skill points in the message window. Would be great if there would be a proper highlighting for each skill check either containing a 1 or 20.

**Comment by Plushtoast** [comment]
Hi,
in the short to medium term we wan't to completely overhaul the display of the roll. Which will make this change unnecessary.
We are currently in contact with r20 for another solution (because ... complicated), but we hope to conclude this soon.
