### ISSUE TITLE
Feature: Token Attribut automatisch belegt (SC/NSC)

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/TDE-Roll20-Official#12]
Ist es möglich, dass bei einem SC/NSC der auf die Szene gezogen wird, automatisch die Verknüpfung zum Attribut des Charakterbogens erstellt wird? 
Oder muss das der GM jedes mal selbst machen?

**Comment by Plushtoast** [comment]
Der Token wird konfiguriert, wann immer die max Le/AsP/KaP geändert werden.
Meines Wissens kann man die Änderung der Tokengrafik derzeit noch nicht tracken.
