### ISSUE TITLE
Tokens bleiben nicht verbunden - Tokens do not stay connected

### ISSUE THREAD

**Issue by HenrikSonntag** [Plushtoast/TDE-Roll20-Official#123]
die tokens bleiben nicht mit dem Charakter verbunden.
wenn ein neuer charakter erstellt wird und ein token mit dem charakter verbunden wird dann schmeißt der charakter den token immer nach dem speicher raus. das passiert nur wenn man den charakterbogen benutzt. 

the tokens are not linked to the character.
when a new character is created and a token is connected to the character, the character always throws the token out after the memory. that only happens when you use the character sheet.

**Comment by Plushtoast** [comment]
Wir sind übrigens mit Roll20 in Kontakt deswegen (das ist meist langsam).
Momentan sieht es so aus, als ob das Problem an Roll20 liegt und nicht am Charakterbogen.

**Comment by Plushtoast** [comment]
Das sollte übrigens inzwischen funktionieren
