### ISSUE TITLE
Weitere Kategorien für Modifikatoren

### ISSUE THREAD

**Issue by MGMartin1522** [Plushtoast/TDE-Roll20-Official#124]
Es könnte Sinn machen, bei der Auswahl von Modifikatoren auch die Oberkategorien (z.B. alle Gesellschaftstalente) auswählbar zu machen, damit man z.B. Erleichterungen und Erschwernisse auf alle Gesellschaftstalente vergeben kann. Außerdem einen Modifikator einführen, der alle Fertigkeitsproben berücksichtigen kann (z.B. einen Malus auf alle Fertigkeitsproben wegen Verstoß der Prinzipientreue).

**Comment by Rusal-Bolsorg** [comment]
Kontext dazu:
Es gibt Kräfte die z.B. einen FW Bonus auf die nächste Körperliche Probe geben. Da man beim Wurf selbst nur Erleichterung eintragen kann ist es immer ein bisschen nervig dann trotzdem rechnen zu müssen.

Z.B. hier
https://ulisses-regelwiki.de/zeremonialgegenstands_sf.html?sonderfertigkeit=Stich+der+St%C3%A4rkung

**Comment by Plushtoast** [comment]
Wird auch ein zusätzliches Popup oder ähnliches geben um pro Wurf QS/FP/FW (und vlt Teilprobenmods) anzugeben

**Comment by Plushtoast** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/11072
