### ISSUE TITLE
Grundregelwerk - Verbessertes Ausweichen weitere Stufen funktionieren nicht

### ISSUE THREAD

**Issue by thomaslazar** [Plushtoast/TDE-Roll20-Official#133]
Wenn mehr als eine Stufe `Verbessertes Ausweichen` benötigt wird, dann wird das nicht im Ausweichenwert berücksichtigt. 

### Soll-Zustand:
* Sonderfertigkeit `Verbessertes Ausweichen` wird auf den Bogen gezogen. 
* Stufe wird auf 2 gesetzt. 
* Sonderfertigkeit wird aktiviert
* Ausweichenwert wird um 2 erhöht. 

### Ist-Zustand:
* Sonderfertigkeit `Verbessertes Ausweichen` wird auf den Bogen gezogen. 
* Stufe wird auf 2 gesetzt. 
* Sonderfertigkeit wird aktiviert
* Ausweichenwert wird dennoch nur um 1 erhöht. 

### Workaround:
Ausweichen +/- auf 2 stellen.

**Comment by Plushtoast** [comment]
See https://github.com/Roll20/roll20-character-sheets/pull/10390
