### ISSUE TITLE
Schild und Nebenhandwaffen können nicht eingetragen/eingegeben/per drag'n'drop hinzugefügt werden. 

### ISSUE THREAD

**Issue by thomaslazar** [Plushtoast/TDE-Roll20-Official#134]
### Ist-Zustand: 
* Neuer Charakterbogen
* Hinzufügen von Kurzschwert aus Kompendium
* Hinzufügen von Schild aus Kompendium
* Nur ein Eintrag ist aktivierbar
* Bereich Schild und Nebenhandwaffen bleiben leer

### Soll-Zustand:
* Neuer Charakterbogen
* Hinzufügen von Kurzschwert aus Kompendium
* Hinzufügen von Schild aus Kompendium
* Beide Einträge sollen aktivierbar sein und dann entsprechend in die Berechnung einfließen

### Workaround:
keiner bekannt

![image](https://user-images.githubusercontent.com/570244/155883695-d1a4cf2f-2dcd-4b61-9484-9e7fbe70bef1.png)

**Comment by Plushtoast** [comment]
Duplicate of #111
