### ISSUE TITLE
Charakterbogen - Im Talente Tab auch andere Sonderfertigkeiten/Vorteile/etc anbieten zum an und ausschalten

### ISSUE THREAD

**Issue by thomaslazar** [Plushtoast/TDE-Roll20-Official#135]
Als Spieler würde ich gerne in der Lage sein im Tab Talente auch neben den Talentsonderfertigkeiten auch andere Sonderfertigkeiten/Vorteile/Nachteile etc. an- und abschalten zu können. 

Z.B. Vorteile wie Zwergennase, Schlangenmensch oder auch Allg. Sonderfertigkeiten wie Ortskenntnis (...) beeinflussen situationsabhängig den Modifikator von Talenten. 

Evtl. könnte man in den Details die Möglichkeit schaffen, über ein Dropdown anzugeben, dass eine bestimmte Sonderfertigkeit auch in anderen Tabs zu sehen ist.

**Comment by Plushtoast** [comment]
Roll20 ist unglaublich beschissen, was die technischen Möglichkeiten angeht. Was du dir da vorstellst rangiert irgendwo zwischen irrem Aufwand, beschissener Performance und unmöglich.
Mal sehen was da noch so kommt.
