### ISSUE TITLE
Kampfsonderfertigkeiten und weiteres

### ISSUE THREAD

**Issue by Shiomifox** [Plushtoast/TDE-Roll20-Official#152]
Hallo liebes Team,

wenn man Kampfsonderfertigkeiten wie Wuchtschlag oder Präziser Stich auswählt und den Schaden auswürfelt, steht im Chatlog immer eine 0. Die richtige Zahl kann man zwar via Mouseover selbst zusammenrechnen, aber 0 ist ja definitv falsch.

Außerdem ist mir aufgefallen, dass beim Gratis Schnellstartabenteuer die Journale nicht wie angegeben auf der Karte platziert wurden. Ebenfalls sind bei den Archetypen einige Talente und Attribute falsch abgetippt worden aus der pdf-Vorlage.

**Comment by Plushtoast** [comment]
Roll20 hat keine einfache Möglichkeit Journale auf der Map zu platzieren.
Wir wolltens machen...geht aber nicht.

Allerdings werden zukünftige Abenteuer das Feature haben, da wir uns inzwischen einen Workaround ausgedacht haben.


Schaden schauen wir uns an.

**Comment by Plushtoast** [comment]
Was genau meinst du mit "steht eine 0"?
![grafik](https://user-images.githubusercontent.com/44941845/160259043-cba62103-8d54-45bf-957a-21c19dd1581d.png)

Ich seh hier keine.

**Comment by Shiomifox** [comment]
Sorry, ich habe die Antwort nicht gesehen. Hier der Screenshot vom Präzisen Stich von Carolan aus dem Schnellstart-Abenteuer.
![Präziser Stich](https://user-images.githubusercontent.com/102359631/160765362-80532182-2c35-40dd-923b-853f92d53176.jpg)

**Comment by Plushtoast** [comment]
Kann das nirgendwo nachstellen, hat sich vermutlich durch r20 oder einen anderen patch erledigt

**Comment by Shiomifox** [comment]
Nein, hat es nicht. Hatten wir gerade diesen Montag erst wieder. Durch aktivierten Modifikator beim TP würfeln, oder wenn eine Kampf-Sonderfertigkeit wie Wuchtschlag oder ähnliches aktiv ist. Gewürfelt wird richtig und man kann es sich selbst zusammen addieren, aber angezeigt wird eine 0

**Comment by Plushtoast** [comment]
Ist bei dir beim TP effekt 2 oder +2 eingetragen?

**Comment by Shiomifox** [comment]
ja gut, Problem erkannt, Problem gebannt. Dankeschön

**Comment by Shiomifox** [comment]
aber kann das nicht geändert werden, dass der das trotzdem akzeptieren würde?

**Comment by Plushtoast** [comment]
Doch ich schau dass das geht

**Comment by Shiomifox** [comment]
cool. weil das einfach intuitiv ist, dass, wenn man -1 einträgt, man auch +1 einträgt und nicht 1

**Comment by Plushtoast** [comment]
Hm geht bei mir auch mit +2. Vlt hab ich das schon vor längerer Zeit gefixt und nur vergessen einzuspielen.
Demnächst wirds n Bugfix Patch geben, falls das Problem dann immer noch da ist, bitte nochmal Bescheid geben.

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
