### ISSUE TITLE
Modifying Off-Hand weapons with "catch blade"  doesn't work properly

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#164]
Hi i tried using the main-gauche as an off hand weapon with the catch blade ability (and the self-made death from left(?).
sadly neither offhand PA+/- nor Of-hand TP++/- seem to have any effects.

Ich versuche einen Linkhand mit den Kampfsonderfertigkeiten "Tod von Links" und "Klingenfänger zu modifizieren. Dafür nutze ich "Nebenhand PA+/-" und "Nebenhand TP +/-"  aber es hat irgendwie nie einfluss auf die Würfe...   ausgerüstet habe ich den linkhand als "nebenhandwaffe"

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
