### ISSUE TITLE
Wurfbefehl aus dem "Text Chat Input"-Feld liefert Fehler

### ISSUE THREAD

**Issue by mellonvo** [Plushtoast/TDE-Roll20-Official#166]
Hallo,
um eine Token-Befehl über "Attributs & Abilities" auszuführen kopiere ich den Wurf-Befehl aus dem "Text Chat Input"-Fenster" und kopiere ihn als neue "Ability".
Für Kampf-Befehle AT oder PA funktioniert dies.
Bei Talenten, Magie oder Götterwirkung liefert dies allerdings den Fehler das gegen "0"-Werte geworfen wird und keine TW-Werte angezeigt werden, folgend auch kein QS oder Erfolg angezeigt wird.
![grafik](https://user-images.githubusercontent.com/103103668/161929094-caded0c8-07ee-44d1-8436-f686beac9cee.png)

**Comment by Plushtoast** [comment]
Roll20 kann das nicht.

**Comment by Plushtoast** [comment]
Die Kombination der drei d20 Probe mit roll20 ist nahezu unmöglich.

**Comment by Plushtoast** [comment]
Hab das auch an roll20 geschrieben. Das selbe Problem verschwendet meine Zeit schon seit Monaten und verhindert neue Features.
Aber meiner Erfahrung nach fixen die eher nix
Ggf kannst du die rowid der repeating section irgendwie zu deiner ability hinzufügen aber keine Ahnung ob oder wie das geht.

**Comment by mellonvo** [comment]
Danke für die Antwort.
Hatte mich nur gewundert, da es mit dem alten DSA5-Bogen funktioniert.

**Comment by Plushtoast** [comment]
Ja ich hatte die Option entweder den 3d20 Wurf sinnvoll darzustellen oder dass die abilities gehen bzw in die tokenbar. Beides zeitgleich scheint aber derzeit unmöglich zu sein.
Und die Übersichtlichkeit erscheint mir dann doch wichtiger

**Comment by mellonvo** [comment]
Die Darstellung zur Unterscheidung der Würfe und in Farbe ist wirklich toll, danke.

**Comment by Plushtoast** [comment]
Danke für dein Feedback. Ich Versuche beides zu ermöglichen aber derzeit erscheint das unmöglich zu sein.

Generell ist das aber interessant zu hören, wie ihr das Sheet benutzt. Wir haben quasi null Info darüber. Also gerne auch mehr Vorschläge, wünsche oder Tipps für andere Spieler (allerdings ohne versprechen).
