### ISSUE TITLE
SF Präziser Schuss keine Änderung Würfelwert

### ISSUE THREAD

**Issue by mellonvo** [Plushtoast/TDE-Roll20-Official#167]
Hi,
bei der SF Präziser Schuss wird die Berechnung beim Wurf richtig durchgeführt, aber die Änderung wird beim Würfelwert und TP-Wert im Charakterbogen nicht angezeigt.

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
