### ISSUE TITLE
Dedizierte Tokens für Charakter Bögen werden nicht gespeichert. 

### ISSUE THREAD

**Issue by thomaslazar** [Plushtoast/TDE-Roll20-Official#170]
Hallo. 

Ich habe das Problem, dass wenn man ein Spiel erstellt mit dem offiziellen DSA5 Char Bogen, dass sich dann bei Charakteren keine dedizieren Token Bilder hinterlegen lassen. 

Dieses Problem kann man hier sehen: https://imgur.com/a/KGDLFkz

Schritte um das nachzuvollziehen (siehe auch Videos oben):

1. Roll20 spiel mit DSA5 Char Bogen starten
2. Char im Journal erstellen
3. Ein Avatar Bild zuweisen
4. Char speichern
5. Ein Token auf die Karte ziehen
6. Token bearbeiten und an Char zuwiesen
7. Char Bogen öffnen und bearbeiten
8. Token auf Karte auswählen
9. Beim Char den default Token löschen und sagen, er soll den ausgewählten nehmen
10. Char Bogen speichern
11. Char aus Journal auf Karte ziehen -> Nimmt Avatar Bild anstatt Token
12. Char Bogen bearbeiten -> Token nicht mehr im Char bogen vorhanden

Das passiert nur im offiziellen DSA Char Bogen. Nicht mit dem TSA oder irgend einem anderen. 

Das lässt für mich darauf schließen, dass es ein Problem mit dem offiziellen Char Bogen. 

Ein Ticket dahingehend bei Roll20 ist auch schon offen.

**Comment by thomaslazar** [comment]
Die Antwort von Roll20:

> Hi there,
> 
>  
> Thanks for reaching out! To clarify, Roll20 does not create all of the character sheets on our site; most of them are actually created by community members, including the publishers! This is one of those cases and, as such, there isn't much we can do for issues that are occurring or changes that need to be made to the sheet directly. If you are having an issue with the sheet or want to see an improvement made, I would highly suggest you post to our [Character Sheet Forum](https://app.roll20.net/forum/category/277980). Most of the character sheet authors tend to frequent that space, so there's a good chance they can help you figure out what's going on or provide a fix. Also, we encourage you to reach out to the publishers themselves. If you contact the publishers, they can reach out to us for assistance to improve the sheet.
>  
> We will also escalate this to our Sheet Development team for review. While we cannot direct provide a solution if it is caused by the sheet itself or an ETA when this issue will be fully reviews, we appreciate your patience. The Development team will see if it is a bug from Roll20 and if it's not, we need the publisher to contact us about their sheet if they need assistance fixing the interaction with the VTT.
>  
> Beyond that though, if you feel like you are having a general issue with Roll20, or there is simply anything else you need, please don't hesitate to let us know!
>  
> 
> Regards,

**Comment by Plushtoast** [comment]
Ist ein Roll20 Bug. Hab aber inzwischen herausgefunden woran es liegt und einen Workaround gefunden.
Leider muss ich dafür eine andere Funktion deaktivieren...
Danke für deine ausführliche Hilfe.

**Comment by thomaslazar** [comment]
Danke für die Info! Welche Funktion muss deswegen abgeschaltet werden? Wenn man fragen darf.

**Comment by thomaslazar** [comment]
Workaround funktioniert. Tokens werden wieder bei Charakteren gespeichert. Danke vielmals dafür. Das macht doch einiges viel einfacher wieder!
