### ISSUE TITLE
Fertigkeiten in Gesellschaftstalente nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by Trestolt** [Plushtoast/TDE-Roll20-Official#173]
Die Fertigkeiten in Gesellschaftstalente sind nicht alphabetisch sortiert. Das erschwert die schnelle Eingabe von Fertigkeitswerten für Held und Tier etc.

![grafik](https://user-images.githubusercontent.com/49414917/167189572-309d459f-8d9f-4d70-a85f-be9900c0f07e.png)

**Comment by Plushtoast** [comment]
Sollte wieder passen
