### ISSUE TITLE
Show the talent/spell value in the roll results.

### ISSUE THREAD

**Issue by thomaslazar** [Plushtoast/TDE-Roll20-Official#174]
I would like to also see the value for talents and spells in the result shown in the chat. 

It would make it easier for me as DM to explain to players why some rolls failed, or what they have to roll if they want to augment a roll with Schips.

**Comment by Plushtoast** [comment]
What value are you specifically talking about? The Fertigkeitswert?

**Comment by thomaslazar** [comment]
Yes. The Fertigskeitswert. But with applied bonus and malus from Sonderfertigkeiten and the like.

**Comment by Plushtoast** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/11036
