### ISSUE TITLE
Armor Handicap attribute maintained as special ability does not effect the handicap status of the armour

### ISSUE THREAD

**Issue by PapaNils** [Plushtoast/TDE-Roll20-Official#178]
my char has an active armor with BE3 (Leichte Platte)

I tried to enter the special ability "Belastungsgewöhnung" to reduce the effect of the armor in the status "Belastung" this does not work.
![image](https://user-images.githubusercontent.com/65504998/171999229-2803dcb9-a526-4528-b67a-cbe97d603d8a.png)
neither the attribute "Belastungsgewöhnung" or the attribute "Belastung" has an effect on the status
![image](https://user-images.githubusercontent.com/65504998/171999285-0fcfcc44-a9ba-44cf-a92b-d1d7bc586578.png)
![image](https://user-images.githubusercontent.com/65504998/171999295-47cfd950-5c7d-44d1-937d-7857849b6f8f.png)

**Comment by mellonvo** [comment]
the ability "Belastungsgewöhnung" is a positive effect, meams enter "2" to reduce the "Belastung" by 2 (-2).
