### ISSUE TITLE
Minor error "Zauberdauer" instead of "Liturgiedauer" for Liturgien (Geweihte)

### ISSUE THREAD

**Issue by mellonvo** [Plushtoast/TDE-Roll20-Official#179]
![grafik](https://user-images.githubusercontent.com/103103668/172995075-cf7b9809-d996-4157-9256-7a1626b3fd9f.png)

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
