### ISSUE TITLE
Name of used Roll20 Template

### ISSUE THREAD

**Issue by Letobili** [Plushtoast/TDE-Roll20-Official#180]
It would be great to know the name of the used roll20 template so that players can create their own good looking macros.

**Comment by Plushtoast** [comment]
Hi, the sheets template is visible here:
https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Das%20Schwarze%20Auge%20(TDE)%205%20OFFICIAL%20by%20Ulisses/dsa5official.html

If you want to use the rolltemplates search for rolltemplate there.

Which looks like this:

```
<rolltemplate class="sheet-rolltemplate-DSA-selbstverletzt">
```
and translates into the rolltemplate name: DSA-selbstverletzt

But I am afraid that your macros will be rather difficult to setup as roll20 does not really support the 3d20 roll well.

**Comment by Letobili** [comment]
Thank you very much!

I just wanted to use it for rollable table macros like "Kritische Treffer" so it works almost perfectly. Small but ignorable problem is that the font size between the inline text and the roll table text is not identical.
![289051566_755537158807291_3529741050596469743_n](https://user-images.githubusercontent.com/108064885/175296541-b282b050-01c7-44e5-8c33-aabb29206d06.png)

**Comment by Plushtoast** [comment]
All rolls should also be draggable to the quickbar of the tokens except the 3d20 rolls.
So especially for combat useful.
Also I think I already added a button on the roll card for combat crits, no?

**Comment by Letobili** [comment]
Crits look like that at the moment. 
![image](https://user-images.githubusercontent.com/108064885/175331111-c0c4380f-c29e-462e-929c-9b2a88f3316e.png)
There is only the "tpx2"-button for crits without the focus and optional rules and not the crit tables from AvKo II.
