### ISSUE TITLE
Fernkampf durch Belastung beeinflusst

### ISSUE THREAD

**Issue by KalElRedK** [Plushtoast/TDE-Roll20-Official#181]
Belastung reduziert Fernkampf, was es nicht sollte da Belastung nur AT, Verteidigung, INI und GS reduziert, nicht FK.

**Comment by Plushtoast** [comment]
Belastung beeinträchtigt auch fernkampf. Schon mal n bogen in ner plattenruestung benutzt?

**Comment by KalElRedK** [comment]
1. Es geht hier nicht um Logik, sondern um die Regeln und das sheet sollte das behandeln und keine Hausregeln von dir.
2. Nicht jede Rüstung behindert beim Schießen, wie z.B. Gambeson.

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
