### ISSUE TITLE
Spezialisierungen werden falsch gewürfelt

### ISSUE THREAD

**Issue by Rusal-Bolsorg** [Plushtoast/TDE-Roll20-Official#187]
Der "F-Würfel" für Spezialisierungen wirft die Probe mit 2 Punkten Erleichterung statt mit 2 Punkten höherem FW
https://ulisses-regelwiki.de/SF_FertigkeitsspezialisierungTalente.html

In diesem Beispiel sind keine anderen Modifikatoren aktiv! 
Der Basis FW beträgt 12, korrekterweise müssten hier 14 FP übrig bleiben.
![image](https://user-images.githubusercontent.com/110888519/183584007-db6b0f41-a43c-439e-b242-37a88819869d.png)

**Comment by Plushtoast** [comment]
Fixed once this pull request is merged:
https://github.com/Roll20/roll20-character-sheets/pull/10908
