### ISSUE TITLE
Implementation of Charaktersheet to Roll20.App

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#207]
There seems to be a way to “make the charaktersheets compatible with the roll20 ios app. 
As this improves the possibility of integrated hybrid games, it could be a selling factor for roll20 products.

**Comment by Plushtoast** [comment]
Required work doesn't justify the outcome for neither customers nor programmers.

**Comment by LordNeilo** [comment]
Without knowing the workload, i feel as if TDE would extremely benefit from letting the sheet roll on a live in-person session. 
Especially considering, that younger players need to be brought into the hobby and those are more used to "easier" systems like DnD and are more likely to use electrical devices to play. 

I'd love to help if this lessens the workload.
