### ISSUE TITLE
Zauber-/Liturgie-Fertigkeitswert verzehnfacht

### ISSUE THREAD

**Issue by mellonvo** [Plushtoast/TDE-Roll20-Official#210]
Seit kurzem werden die Fertigkeitswerte von Zaubern und Liturgie bei der Probe verzehnfacht.
Bin nicht sicher, ob es mit dem update des Charakterbogens zu tun hat.
![Unbenannt](https://user-images.githubusercontent.com/103103668/196765330-2423c8fe-7e04-4ef4-909d-aec153c92418.PNG)

**Comment by Plushtoast** [comment]
Hast du FW oder FP aus einer anderen Quelle? Sonderfertigkeit oder so?

**Comment by Plushtoast** [comment]
Fixed with https://github.com/Roll20/roll20-character-sheets/pull/11139

**Comment by mellonvo** [comment]
Nein, das tritt bei verschiedenen Charakterblättern gleich auf.
Du hast es als fixed markiert, wie bekomme ich die Korrektur ins Charakterblatt?
Passiert das automatisch?
Im Vorraus schon Danke

**Comment by Plushtoast** [comment]
Passiert automatisch sobald roll20 die Änderung integriert.
Das dauert normalerweise 1 bis 7 Tage
