### ISSUE TITLE
bug with botches in ranged combat

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#217]
it seems that the botch table used for ranged combat is not the good one. it uses the botch table for close combat

it is probably due to the code line 25264

`<button type="roll" name="roll_attacke_fk" class="dieButton" value="@{output_option} &{template:DSA-combat} {{bestaetigungswurf=[^{bestaetigungswurf}](~bestaetigungswurf)}} {{bestroll=[[@{deactivateConfirmationRoll}]]}} {{hitzone=[[@{fk_hitzone}]]}} {{defenseMalus=[[@{defenseMalusFK}]]}} {{attribute0=mut}} {{name=@{fk_name}}} {{subtags=^{attacke}}} {{wurf=[[1d20cs1cf20]]}} {{wert=[[(@{fk_roll}+@{gesamt_fk_mod}+@{mod_option}+@{kampf_modifier})]]}} {{mod=[[(@{gesamt_fk_mod}+@{mod_option}+@{kampf_modifier})]]}} {{dmg=[^{TP}](~tp_fk)}} {{dmgCrit=[^{x2}](~tp2_fk)}} {{botch=[^{patzer}](~nahkampf-atpa-patzer)}} {{critresult=^{forceHalfParry}}}">`

problem for me is to use **~nahkampf-atpa-patzer** instead of **~fernkampf-patzer**

**Comment by dyvim** [comment]
for example my player rolled a 4 and should have his bow broken with a malus of -4 to AT but the roll whoed a malus of -2 AT and -2 PRD

**Comment by Plushtoast** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/11199
