### ISSUE TITLE
Seit v1.5.9 ist das Sheet nicht mehr auf Deutsch verfügbar

### ISSUE THREAD

**Issue by JohnDorean** [Plushtoast/TDE-Roll20-Official#230]
Trotz dessen, dass der Roll20 Account auf Deutsch eingestellt ist, ist das Sheet auf Englisch.

**Comment by Plushtoast** [comment]
Roll20 hat abgeändert wie sie Übersetzungen handhaben. Englisch muss nun die standard Sprache sein. Zusätzlich haben sie die deutsche Übersetzung mit spanisch vermischt und anschließend gelöscht. Eine Lösung ist in Arbeit...

**Comment by Plushtoast** [comment]
Roll20 hats gefixt.
Gerne auch noch bisschen Feedback da lassen oder Wünsche äußern (ob sie erfüllt werden können is eine andere Frage)
