### ISSUE TITLE
Character Sheet translation

### ISSUE THREAD

**Issue by rasmusgrote** [Plushtoast/TDE-Roll20-Official#231]
Hi,
I played with the character sheet over the last year and the language was always german. My Profile in Roll20 is also German but today the character sheets for me and all my players where in english. So we double checked but everyone has selected german as the default language in Roll20. In the changelog was an entry a few days ago:

Changed default language translation file to en in respect to roll20 new translation system.

So how do I change the language back to german now? I'm a bit confused right now.

**Comment by rasmusgrote** [comment]
https://github.com/Plushtoast/TDE-Roll20-Official/issues/230

**Comment by Plushtoast** [comment]
See #230

**Comment by Plushtoast** [comment]
Roll20 hats gefixt.
Gerne auch noch bisschen Feedback da lassen oder Wünsche äußern (ob sie erfüllt werden können is eine andere Frage)
