### ISSUE TITLE
Würfelsymbole werden im Chat nicht angezeigt.

### ISSUE THREAD

**Issue by Rusal-Bolsorg** [Plushtoast/TDE-Roll20-Official#233]
![image](https://github.com/Plushtoast/TDE-Roll20-Official/assets/110888519/c21d1f03-6266-4510-a279-a7c2e4be581a)

Sieht so aus wären die Bilder im Backend nicht mehr da. und wären durch Platzhalter ersetzt worden.

**Comment by Letobili** [comment]
Gerade getestet. Bei mir ebenfalls.

**Comment by Plushtoast** [comment]
Bilder sind da. Fehler muss irgendwo bei Roll20 liegen. Müssen wir kontaktieren

**Comment by Letobili** [comment]
Fehler wurde von Roll20 anscheinend gerade behoben.
