### ISSUE TITLE
Charakterbögen sind (zumindes bei mir) zerrissen / nicht im normalen Format

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#30]
<img width="1420" alt="Bildschirmfoto 2021-09-20 um 18 26 06" src="https://user-images.githubusercontent.com/34488783/134038839-7353cf24-39a3-4d4f-b63f-5c4606a2bb75.png">

Sowohl wenn ich vorhandene oder neue Charaktere öffne um das Charakterblatt einzusehen, sehe ich diese "unformatierte" Textwand.
Ich nutze Goolge Chrome Version 93.0.4577.82   auf macOS Monterey 12.0beta

**Comment by Plushtoast** [comment]
Aus Versehen css nicht kopiert. 
Bitte einmal refreshen.
