### ISSUE TITLE
Bei allen Einträgen im Journal die einen Preis oder ein Gewicht haben, fehlen Angaben zur Einheit.

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#31]
Im Journal stehen keine Einheitenangeben bei  Preis und Gewicht. Es ist zwar durchgehend Silbertaler und Stein. Das ist aber auch nicht "zentral ersichtlich" und kann so ggf. zu verwirrung führen.

Beispielhaft "Gift" "Kelmon"
<img width="781" alt="Bildschirmfoto 2021-09-20 um 18 51 36" src="https://user-images.githubusercontent.com/34488783/134042303-b7add529-2430-4f15-9714-c326da364c8a.png">

**Comment by Plushtoast** [comment]
Hm, zu irgeneinem Zeitpunkt soll das Charakterblatt auch noch das Ausrüstungsgewicht automatisch addieren und entsprechend die Belastung ausrechnen und anwenden. Spätestens dort ist das dann mit dem Gewicht klar.

Auch wäre es möglich Gegenstände bei Drag & Drop zu bezahlen Das lässt sich in Roll20 aber vermutlich nicht vernünftig per GUI umsetzen.
