### ISSUE TITLE
Die "Aktionsdauer" bei Ritualen, Zaubern, Liturgien und Zeremonien hat keine Einheitenangabe.

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#37]
Dadurch, dass bei der "Aktionsdauer" keine Einheitenangabe gemacht wurde und manche Zeiten in Aktionen umgerechnet wurden, passierten ein paar Fehler. 

Dschinnenruf z.B. wird mit 480 angegeben. Hier müssen Minuten gemeint sein, da der Dschinnenruf laut RegelWiki 8 Stunden dauert.  (Gleiches beim Ackersegen, bei dem 120 angegeben ist, dieser braucht ebenfalls 2 Stunden. 

Im Gegensatz dazu wird der Analys Arkanstruktur mit 32 angegeben, das sind jetzt aber Aktionen. 

<img width="781" alt="Bildschirmfoto 2021-09-20 um 20 23 42" src="https://user-images.githubusercontent.com/34488783/134054413-0eb2c19a-81c2-4b73-bfb6-5019a00c627f.png">

<img width="781" alt="Bildschirmfoto 2021-09-20 um 20 22 57" src="https://user-images.githubusercontent.com/34488783/134054406-72bb7c66-8b3a-42e3-977c-a59ddc9e436d.png">

Während man das zwar inhaltlich versteht, wenn man sich gut genug mit Ritualen (Zeremonien) und Zaubern (Liturgien) auskennt, ist es trotzdem verwirrend.

**Comment by Plushtoast** [comment]
Beides normiert auf Minuten bzw Kampfrunden zwecks potentieller Automatisierung.
Einheit kommt aber dazu.
