### ISSUE TITLE
Funktion: Token Attribut LE immer noch nicht automatisch belegt.

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/TDE-Roll20-Official#39]
Leider ist es immer noch so, wenn ich einen Akteuer aus dem Kompendium ziehe, dann ist beim Token das Attribut nicht verknüpft. Das bedeutet, dass die Lep Änderungen nicht an den Char übertragen werden:

![grafik](https://user-images.githubusercontent.com/80099175/134125522-4e721d7a-b1c5-49d7-8dff-cf9ca90b3b24.png)

**Comment by Plushtoast** [comment]
Roll20 hat aktiv davon abgeraten Token zu linken. Scheinbar führt das zu Problemen.
Mal sehen, ob wir diesen Ratschlag einhalten oder nicht.

**Comment by tomsaath** [comment]
Okay, vielleicht wissen das die Roll20 User ja auch? Ich selbst komme ja von Foundry und sehe es deshalb vielleicht so kritisch?

**Comment by Plushtoast** [comment]
Du musst den Actor, sofern er schon mal vor der Änderung importiert war, erst wieder löschen.
Der Link müsste danach gehen.

**Comment by Plushtoast** [comment]
Sieht so aus als ob das Link nur in eine Richtung funktioniert.
Vom charaktersheet aus das Attribut ändern aktualisiert den Token. Andersherum nicht.

Schätze Roll20 geht das nicht, lässt sich auch nichts dazu finden.

**Comment by tomsaath** [comment]
Komischerweise klappt es aber, wenn du in den Token Settings bei Attribut "le" auswählst:
![grafik](https://user-images.githubusercontent.com/80099175/134641772-ac5548a5-dd30-4067-b1d7-794f73970b1e.png)

**Comment by Plushtoast** [comment]
ok hab den fehler gefunden.
scheinbar kann man das tatsächlich absichtlich so konfigurieren, dass es auch nur in eine richtung gehen würde.
die frage ist, wozu wäre das gut...

**Comment by tomsaath** [comment]
Frag mich nicht. In der Regel will man bei Spielern ja die Verbindung bei Monstern nicht. Kannst du das getrennt einstellen? Wenn nein, ist das vielleicht der Grund warum es sich so verhält?
