### ISSUE TITLE
Funktion: Einzelne Würfelergebnisse mit im Chat ausgeben

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/TDE-Roll20-Official#40]
Ich finde die Formel im Chat sehr intransparent und ohne 3D Würfel sieht man überhaupt nicht auf den ersten Blick was gewürfelt wurde. Für mich gehört das aber zum Gefühlt im PnP dazu. 

Ist aber vielleicht ein sehr individuelles Problem.

**Comment by tomsaath** [comment]
Prio User: medium

**Comment by Plushtoast** [comment]
Sehe ich genauso. Roll20 ist für den 3d20 Wurf aber nicht richtig gewappnet, weswegen das sehr umständlich ist.
Die Würfeleinstellungen sind noch 1zu1 TSA Bogen.

**Comment by tomsaath** [comment]
Du weißt ich spiele nicht mit dem Roll20 Bogen, dementsprechend kann ich dir dazu nichts sagen.
