### ISSUE TITLE
Idee: Fertigkeiten Anzeige der Talente zu Werten umschalten

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/TDE-Roll20-Official#41]
Ich glaube, dass es hilfreich sein könnte, die Eigenschaften in den Talentproben umschalten zu können. Damit meine ich, nicht die Eigenschaft, sondern den Wert der Eigenschaft in der Übersicht sehen zu können.

![grafik](https://user-images.githubusercontent.com/80099175/134127570-da317d61-1f67-48b3-866f-fd3372a7e1ee.png)

Prio User: Low

**Comment by Plushtoast** [comment]
Die Attrbute werden in der Kopfzeile nochmal etwas prominenter dargestellt.
Das sollte dann reichen.
Ggf bekommen die Attribute aber noch die entsprechende Hintergrundfarbe.
