### ISSUE TITLE
Funktion: Zuständen - Stufe über das Feld schreiben

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/TDE-Roll20-Official#42]
Ich glaube es würde helfen wenn über die Felder der Zustände noch die Stufen geschrieben werden. So erkennt man auch leichter, dass das erste Feld für 0 oder kein Zustand steht.

Prio User: medium

![grafik](https://user-images.githubusercontent.com/80099175/134128810-ffcd947b-58a5-4d5a-b8f9-f8c62750410c.png)

**Comment by Plushtoast** [comment]
Für Stufe 0 bräuchte ich eigentlich irgendein anderes Icon.
Mülltonne zb...aber zu modern.
