### ISSUE TITLE
Fehler: Nahkampf ist leer und wir nicht mit Raufen Werten belegt.

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/TDE-Roll20-Official#43]
Anscheinend scheint etwas mit den Nahkampfwerten nicht zu klappen. In meinen Charakteren ist das überall auf 0 obwohl Raufen ja immer einen Wert von 6 und somit auch berechenbare Werte hat.
![grafik](https://user-images.githubusercontent.com/80099175/134130963-53542760-79a7-42f7-af89-97ace12d29a5.png)

**Comment by Plushtoast** [comment]
Man muss eine Waffe "Raufen" anlegen und diese entsprechend konfigurieren.

**Comment by tomsaath** [comment]
Ah, zum Thema Raufen. Du musst eine Nahkampfwaffe auswählen und kannst auf dem Platz immer nur eine auswählen? Und man kann nur freie hinzufügen aber keine weitere Waffe auf der Seite des Bogens aus der Ausrüstung aktivieren?
