### ISSUE TITLE
Funktion: Profession mehrfach ziehen vervielfacht Fertigkeitspunkte

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/TDE-Roll20-Official#47]
Wenn die Profession mehrfach in den Charakterbogen gezogen wird, dann werden die Fertigkeitspunkte erneut addiert. Optimal wäre, bei einem zweiten Import nichts mehr zu tun, glaube ich.

**Comment by Plushtoast** [comment]
Ich denke das sollte über die Abfrage, ob man das Paket hinzufügen will ausreichend abgesichert sein.
