### ISSUE TITLE
Im Journal funktioniert die "View all ..." nicht

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/TDE-Roll20-Official#5]
Einzelnen Journal Eintrag öffen und danach auf "View all ..." am Seitenende klicken

**Comment by LordNeilo** [comment]
Ich habe mal als beispiel diese 2 Screenshots gemacht, vielleicht erklärt das die Problematik besser:

<img width="922" alt="Bildschirmfoto 2021-09-19 um 20 51 18" src="https://user-images.githubusercontent.com/34488783/134040652-21d962df-5982-4df2-9bf3-97a09f1aaa17.png">
<img width="728" alt="Bildschirmfoto 2021-09-19 um 20 51 00" src="https://user-images.githubusercontent.com/34488783/134040786-68106741-be49-4eed-a0d9-f54bb5eaf747.png">

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/134049790-452cac43-9b08-4595-a890-4432ea7f6e71.png)

Funktioniert bei mir.
Meine Vermutung ist, dass das bei einem nicht releasten Compendium nicht richtig gesharet ist und sich von alleine löst, sobald das Dingens raus ist.
