### ISSUE TITLE
Beschreibungen bei Kreaturen bei Drag & Drop unvollständig

### ISSUE THREAD

**Issue by Murm3lt13r** [Plushtoast/TDE-Roll20-Official#56]
Feuerdschinn Beschreibung und Bild fehlt
Hund Beschreibung fehlt

Fehlermeldung Console:
![image](https://user-images.githubusercontent.com/75448500/134481579-af5aed29-cb40-4b7a-a790-4ed759df622e.png)

Beispiel:
![image](https://user-images.githubusercontent.com/75448500/134481699-b325ea22-08e5-4d5c-ba58-2544e564d5e1.png)

**Comment by Plushtoast** [comment]
Lag daran , dass bereits eine andere version des tokens importiert ware. siehe gespräch
