### ISSUE TITLE
Qualitätsstufen bei Verbrauchsgütern

### ISSUE THREAD

**Issue by Murm3lt13r** [Plushtoast/TDE-Roll20-Official#65]
Antidot - Heiltrank - Liebestrunk - Unsichtbarkeitselixier - Verwandlungselixier - Waffenbalsam - Willenstrunk - Zaubertrank 

"<br/>" durch "-" ersetzen

**Comment by Plushtoast** [comment]
Formatier das mal für alle handisch um, so dass du denkst, dass es gut aussieht.
Anschließend bau ichs für zukünftige Module ein.
Im schlimmsten Fall müssen, wir die QS als einzelne Attribute machen, wobei das auch nixig is...
