### ISSUE TITLE
Import aus Tsa Bogen überträgt keine Ausrüstung

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#67]
Keines der Items des Ausrüstungs-Reiters (NAhkampf, Fernkampf, Rüstung, Geld, Inventar) werden vom TSA Bogen (im Vault) übernommen.

**Comment by Plushtoast** [comment]
Ok bitte nochmal versuchen.

Inventar ist nur ein Textfeld und sollte dort auch auf dem neuen Bogen wiederzufinden sein.
Auch werden nicht alle Attribute komplette übernommen (z.b. keine Strukturpunkte)

Desweiteren werden die Gegenstände nicht mit dem Kompendium verknüpft oder mit Daten aus dem Kompendium erweitert.

**Comment by LordNeilo** [comment]
Ausrüstung funktioniert jetzt sehr gut!
