### ISSUE TITLE
Beim Import von Tsa-Bogen Chars aus dem Vault sind die Tokens erratisch

### ISSUE THREAD

**Issue by LordNeilo** [Plushtoast/TDE-Roll20-Official#68]
Bei drei der von mir Importierten Charakteren aus dem Vault haben die Tokens drei unterschiedliche "Verhalten" an dan Tag gelegt:
Huldr Token hat LeP und KaP übernommen, aber keine Farbcodierung.
Henryk hat weder LeP noch AsP noch die Farbmarkierung übernommen.
Graubart hat LeP nicht übernommen, dafür aber seine Farbmakierung.

<img width="434" alt="Bildschirmfoto 2021-09-28 um 21 03 47" src="https://user-images.githubusercontent.com/34488783/135149838-72d92fb6-ef16-4aaf-aa0e-f2d5d44215aa.png">

<img width="434" alt="Bildschirmfoto 2021-09-28 um 21 03 34" src="https://user-images.githubusercontent.com/34488783/135149824-78655e1a-5043-46f3-b147-aab6bc77e0ee.png">

<img width="434" alt="Bildschirmfoto 2021-09-28 um 21 03 55" src="https://user-images.githubusercontent.com/34488783/135149802-f7d7ca30-80d6-48a5-b523-a9d9d0d265e3.png">

**Comment by Plushtoast** [comment]
Das ist vermutlich ein Folgefehler, aus der missglückten Migration der Ausrüstung.
Bitte auch nochmal testen, möglicherweise ist das durch das Migrationsupdate erledigt.

**Comment by LordNeilo** [comment]
Nach dem Migrationsupdate werden LeP, AsP usw. leider garnicht mehr bei den Tokens direkt übernommen.

**Comment by Plushtoast** [comment]
Ich denke du musst die Charsheets einmal öffnen bevor du sie auf die map ziehen kannst.
Mir wäre nicht bekannt wie das in roll20 anders zu lösen wäre, geht vermutlich einfach nicht.

**Comment by LordNeilo** [comment]
Ich habe die chars noch einmal gelöscht und neu aus dem Vault importiert. 
Danach habe ich die Charaktere geöffnet.
Erst anschließend per Drag&Drop vom Reiter Notizbuch auf die Karte gezogen. 
Jetzt werden leider manche der Tokens nicht mehr importiert, sondern das Bild "klein gemacht"
Und leider fehlt immernoch bei Graubart die LePs...

<img width="434" alt="Bildschirmfoto 2021-10-01 um 15 27 20" src="https://user-images.githubusercontent.com/34488783/135628067-c13ea726-b4bf-46e1-a5bd-54f9585a61bd.png">
