### ISSUE TITLE
Würfeltemplate: bei der Farbwahl ist die rote 20 kam zu erkennen

### ISSUE THREAD

**Issue by Trestolt** [Plushtoast/TDE-Roll20-Official#70]
Ist ein einer Probe eine 20 enthalten, wird das Ergebnis rot dargestellt, was bei dem Farbschema des Rolltemplates nicht gut zur Geltung kommt

**Comment by Plushtoast** [comment]
Die Farbe ist wurst.
Es sollte darunter stehen, kritischer Erfolg oder Misserfolg.
Wenn das fehlt, ist es ein Problem.

Außerdem werden wir etwas später das Rolltemplate so abändern, dass alle Würfel als Icon dargestellt werden.
Leider kann man so die Rolls nicht mehr per drag and drop in die quickbar ziehen.
Was ein Nachteil ist, aber so ist Roll20 eben wie du vermutlich weißt :)

**Comment by Trestolt** [comment]
ja, ist schwierig, wobei Roll20 sich da ja auch erneuert, da gibt es neue Features.
Die Meldung darunter habe ich jetzt erst gesehen :-)
