### ISSUE TITLE
Nach Import eines SC wird der Bogen als Mix aus SC/NSC dargestellt

### ISSUE THREAD

**Issue by Trestolt** [Plushtoast/TDE-Roll20-Official#74]
nach Import von SC:
- es werden die NSC Stats mit angezeigt, z. B. Grundwerte, wird  evtl. das NSC Flag nicht richtig gesetzt?
- Im Kampf werden ebenfalls NSC Elemente angezeigt

**Comment by Plushtoast** [comment]
Also der neue Bogen hat ja ein radio button für nsc statt check boxes.
D.h. es geht nur noch entweder oder. 
Meine Vermutung ist jetzt (sofern du von Charaktervault Charakteren redest), dass diese Chars zuvor keine Einstellung für die Check box hatten und dein Charbogen das anders gehandlet hat.
Kannst du mal den NPC Bogen hin und her switchen und sehen, ob das dann richtig dargestellt wird?

**Comment by Plushtoast** [comment]
Falls das der Fall ist, müsste ich für toggle_npc beim migrieren einen standard wert festlegen sofern der wert leer ist.

**Comment by Trestolt** [comment]
ja, es geht um Charaktere aus dem Vault. wenn ich den NPC Bogen an und abschalte ist alles wieder gut.

**Comment by Plushtoast** [comment]
Kannst du Mal den char frisch importieren und mir sagen, welcher das ist. Dann schau ich mir das noch genauer an.
