### ISSUE TITLE
the npc part of the sheet is still displayed when you check npc-sheet off in the options

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#85]
![image](https://user-images.githubusercontent.com/8790994/140432865-142b81f2-b350-46dc-a5ba-e56cd07133ae.png)
![image](https://user-images.githubusercontent.com/8790994/140433002-f01405f8-6a2d-41f4-9836-6070ef7e0eb4.png)
![image](https://user-images.githubusercontent.com/8790994/140433069-e2b2ab5f-7e25-4b34-893b-dfb60086613b.png)

**Comment by Plushtoast** [comment]
Is this an imported or preexisting character?

**Comment by dyvim** [comment]
it was a tsa edition character initially.

i didn't import him via the vault. i just changed the type of sheet of my game from tsa edition to ulisses official.

**Comment by Plushtoast** [comment]
I can't tell why this is happening exactly but switching the npc button back and forth should fix this.

**Comment by dyvim** [comment]
you're perfectly right, it works.
thanks 
(i thought i tried this solution already but it wasn't the case)
