### ISSUE TITLE
data-i18n key Peitschen is missing in the translation.json file

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#92]
the data-i18n key "Peitschen" although present in the html file (line 12396 data-i18n-list-item="Peitschen") is missing in the translation.json file.

can you please add it?

BRgds

**Comment by dyvim** [comment]
i've found an other key that is missing : data-i18n="MagieundGlaube" (line 1636 and others)

**Comment by dyvim** [comment]
it could be a good idea to generate a new translation.json file (and make a file compare)
a priori only the translation.json has to be redelivered (and not all the separate translation files for each language)

**Comment by dyvim** [comment]
an other error in the translation.json
for the data-i18n key "beidhaendigerkampf", the value is "Beidhändig" when in the html file it is "Beidhändig Kampf"
it caused some wrong translations...

**Comment by Plushtoast** [comment]
See:
https://github.com/Roll20/roll20-character-sheets/pull/9802

**Comment by Plushtoast** [comment]
What's the fuzz about the "Peitschen" key. You requested me to add this.

**Comment by dyvim** [comment]
one key is needed for Peitschen, but not two (lines 472 and 473). I don't care if the key is named "peitschen" or "Peitschen" as long as it is written the same way everywhere (translation.json and html file).

**Comment by Plushtoast** [comment]
It is already everywhere peitschen except for the data list, but inthis list all ids are uppercase. So it was never a problem.

**Comment by dyvim** [comment]
and so in the translation.json, you only need one line for peitschen
at the moment you have two lines : one with peitschen and one with Peitschen. The second one is not needed.
That was my point
