### ISSUE TITLE
Modifikatoren durch Stati und Effekte

### ISSUE THREAD

**Issue by CytisusBroom** [Plushtoast/TDE-Roll20-Official#93]
Beim berechnen der AT und PA Werte ist es durch die Belastungsgewöhnung zu Fehlern gekommen.
Wenn man Belastungsgewöhnung aktiviert hat und die Rüstung aus dem Inventar entfernt, oder wenn man den Status Belastung manuel ändert stackt der Bonus bzw. Malus auf AT und PA. 
Was genau passiert ist mir nicht ganz klar. Jedenfalls bekam ich irgendwann +12 und -12 auf die besagten Werte obwohl ich keinerlei Sonderfertigkeiten oder Status Aktiv hatte.
Ich hoffe der Hinweis ist hilfreich. Der Fehler war schwer zu finden und sorgte fast dafür dass wir Roll20 für DSA wieder verwerfen.
Im TSA-Bogen konnte ich das Problem auch schon beoachten.

**Comment by Plushtoast** [comment]
Kannst du Schritt für Schritt aufführen was zu diesem Fehler führt?
Ich kann das nicht nachstellen.

**Comment by dyvim** [comment]
I've encoutered the same bug with a player that use dual wielding weapons.
It seems that in some case the bonus/malus are applied when you activate special abilities but are not removed when you disable the special ablity.
so the bonus/malus keeps additionning and reach very high values
the only solution in the tsa edition was to edit directly the values in the panel that lists all values
in the new offical sheet , the bonus are displayed in a specific and editable field so it's easier to correct

**Comment by Trestolt** [comment]
Beobachtet habe ich das Problem auch schon, leider konnte ich es nie nachvollziehen.
Ich habe da  zwei Verdachtsfälle, die ich allerdings bisher nicht nachstellen konnte. 
1.) beim Eingeben oder Ändern eines Modifiers in den Sonderfertigkeiten bleibt man mit dem Cursor im Feld und aktiviert/deaktiviert dann die Sonderfertigkeit. Dabei kommt es zu einem Mix beider Events und es werden in der falschen Reihenfolge die Werte gespeichert.
2.) Der Bogen ist mit der Berechnung mit den Werten noch nicht fertig und es werden neue Events ausgelöst (z. B. aktivieren von Sonderfertigkeiten)

Korrigieren lässt sich das Problem, wenn man alle Sonderfertigkeiten und Effekte deaktiviert und vom Character Sheet zum Tab Attributes & Abilities wechselt und dort nach den Variablen at_sf_mod, pa_sf_mod, tp_sf_mod etc. sucht und diese auf 0 setzt.

**Comment by Plushtoast** [comment]
Ok das klingt nach einem guten Tip, wo ich ansetzen kann.
Kriegen wir weg.

**Comment by CytisusBroom** [comment]
Trestold beschreibt genau das was wir gemacht haben um das Problem zu lösen.
Das ist der richtige Ansatz.

Plushtoast ***@***.***> schrieb am Di., 9. Nov. 2021, 14:50:

**Comment by Plushtoast** [comment]
Falls das so ist wie Trestolt es beschreibt, werde ich wahrscheinlich die komplette Berechnung neu schreiben müssen

**Comment by CytisusBroom** [comment]
Oje, dass klingt nach viel Arbeit.
Es ist für unsere Gruppe essentiell, dass die Berechnungen funktionieren. Für uns entscheidet so etwas ob wir in Roll20 spielen oder woanders.
Ich kann mir vorstellen, dass andere Gruppen ähnlich denken.
Wir freuen uns sehr auf die gute Arbeit, die hier geleistet wird.

**Comment by Trestolt** [comment]
@Plushtoast ich erweitere das Thema noch um einen weiteres Beispiel, was nicht durch Wildrumklicken entsteht, sondern durch das Drag & Drop einer Sonderfertigkeit.  Beispiel: Bambrosch hat AW 7 , -1 durch Belastungsgewöhnung.
Nach Drag & Drop von Verbessertes Ausweichen wird SF_AW auf -1 gesetzt und AW_ROLL = 5. Obwohl die SF nicht aktiviert ist. Wird die SF aktiviert, wird AW +1 gerechnet.  Lösche ich die deaktivierte SF und ziehe sie erneut rein, wird SF_AW = -2 und AW_ROLL = 4 usw.

**Comment by Trestolt** [comment]
Gefühlt passiert das bei allen Sonderfertigkeiten, bisher getestet:
- Verteidigungshaltung
- Verbessertes Ausweichen
- Wuchtschlag
- Präziser Schuss

das sieht so aus, als ob die Funktion change_modifier entweder in der falschen Reihenfolge oder mit verkehrten Vorzeichen ausgeführt wird

**Comment by Plushtoast** [comment]
Hat einer von euch einen Pro Account und Lust die neue Version ein bisschen zu Testen?

**Comment by Trestolt** [comment]
Wenn du die DSA Beta Gruppe C aktualisierst, kann ich auch da testen.

**Comment by Plushtoast** [comment]
Sollte hiermit erledigt sein:
https://github.com/Roll20/roll20-character-sheets/pull/9802
