### ISSUE TITLE
Würfeltemplate Fernkampf wertet eine 20 nicht als Misserfolg oder Patzer

### ISSUE THREAD

**Issue by Trestolt** [Plushtoast/TDE-Roll20-Official#95]
20 gewürfelt bei Fernkampfattacke wird als Erfolg gewertet und nicht als Mißerfolg oder Patzer (FK Wert 14 +6) 

![grafik](https://user-images.githubusercontent.com/49414917/141362115-ff486993-7843-412a-ad24-7c4726432eff.png)

**Comment by Plushtoast** [comment]
See:
https://github.com/Roll20/roll20-character-sheets/pull/9802
