### ISSUE TITLE
Default tokens will not save

### ISSUE THREAD

**Issue by andrewm9** [Plushtoast/TDE-Roll20-Official#96]
When attempting to save a default token with a character, it will not do so. The token will remain visible on the play area, but will not save in teh default slot on the character sheet. Instead it will maintain the normal picture and when dragged out use that as the default token.

**Comment by Plushtoast** [comment]
So I guess you r trying to change the default token for a pregenerated character?
Is this right?
There is nothing we are doing with the images in the implementation. So this must be a r20 bug.
I'll forward this to r20 and that's it...

But it seems like this is working for manually created characters.
So as a workaround you can create a manual char and then drag and drop a predefined actor onto the sheet.
I'll then populate all the data (might take a moment) but not the token or avatar, which will allow you to change them manually.

**Comment by andrewm9** [comment]
> So I guess you r trying to change the default token for a pregenerated character? Is this right? There is nothing we are doing with the images in the implementation. So this must be a r20 bug. I'll forward this to r20 and that's it...
> 
> But it seems like this is working for manually created characters. So as a workaround you can create a manual char and then drag and drop a predefined actor onto the sheet. I'll then populate all the data (might take a moment) but not the token or avatar, which will allow you to change them manually.

No actually this happens with manually created characters as well. Originally, I translated a game from the Tsa edition character sheet. So, I thought it must be a character translation issue so I created a new character in the same game, but it too had the same issue. Next I tried creating a new game with manual characters but it also has the same issue for me.

I realize this may be a Roll20 issue, but I wanted you to be aware of what happened.

**Comment by Plushtoast** [comment]
I forwarded this to r20. And I'll write a note once I received more information.

**Comment by Plushtoast** [comment]
This should be working in the meantime
