### ISSUE TITLE
little error in dsa5official.html about Peitschen

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#98]
line 12397 the code is   `<span data-i18n="lanzen">Peitschen</span>`
when it should be   `<span data-i18n="peitschen">Peitschen</span>
`
it causes problems with the translations (but not with german language) as Peitschen is translated the same way as Lanzen

**Comment by dyvim** [comment]
i've found an other error

line 10032 and 10403 `   <span class="col20" data-i18n="wirkungsdauer">Wirkungsdauer</span>`
this key and its wording are called **Wirkungsdauer** when in fact it should be **Zauberdauer** as there is no Zaubermodifikationen/Spell Modification that allow to modify the Wirkundsdauer/duration, only the Zauberdauer/casting time.

it caused some wrong translations

**Comment by Plushtoast** [comment]
See:
https://github.com/Roll20/roll20-character-sheets/pull/9802
